# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.expedition.node.bb_main] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bb_main set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.expedition.node.airship_base] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_airship_base set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.expedition.node.airship_motor] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_airship_motor set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.expedition.node.motor_back] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_motor_back set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.expedition.node.propeller] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_propeller set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.expedition.node.propeller_underside] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_propeller_underside set from storage animated_java:gu out