# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '1fbcffb9aa56522ad250d1feaaa7a8fb787f8c9b3f2e4a55b7c20ec5e8d98c82'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack