# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.expedition.root] run return 0
execute on passengers run rotate @s ~ ~
execute at @s on passengers run rotate @s ~ ~
execute as @e[type=minecraft:happy_ghast,tag=airship,limit=1,sort=nearest] at @s run tp @e[type=minecraft:item_display,tag=aj.global.root,limit=1,sort=nearest] ~ ~ ~ ~ 0
execute as @e[type=minecraft:happy_ghast,tag=airship,limit=1,sort=nearest] at @s run tp @e[type=minecraft:interaction,tag=totp,limit=1,sort=nearest] ~ ~2.5 ~